### ISSUE TITLE
install_dependencies error

### ISSUE THREAD

**Issue by RangeOfGlitching** [cortictechnology/heartrate_estimation#3]
### ENV

> ubuntu  22.04
> anaconda python 3.8
> OAK-D Lite

---

```
pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.1.0.25 (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66)
ERROR: No matching distribution found for opencv-contrib-python==4.1.0.25
```
```
python main.py 
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    App = getVitalApp(pixel_threshold=args.pixel_thresh)
  File "main.py", line 18, in __init__
    self.processor = HeartrateEstimator(pixel_threshold=pixel_threshold)
  File "/home/dodo/PycharmProjects/depthai/heartrate_estimation/heartrate_estimator.py", line 51, in __init__
    self.ft = cv2.freetype.createFreeType2()
AttributeError: module 'cv2.cv2' has no attribute 'freetype'

```

**Comment by brunocous** [comment]
I got the same error with a similar setup.

**Comment by RangeOfGlitching** [comment]
I made it work at the end.
But the accuracy is not well, especially when the people is not stationary.

**Comment by liuli2008212** [comment]
> I made it work at the end. But the accuracy is not well, especially when the people is not stationary.


How did you solve the problem？

**Comment by RangeOfGlitching** [comment]
It for a while, if memory serves me well, I just command out some code.
Maybe I can look at the code if you want. But only if I still keep the code
